### ISSUE TITLE
Liquid syntax error (line 6): Unknown tag 'plausible'

### ISSUE THREAD

**Issue by lobothijau** [bt-rb/bridgetown-plausible#14]
I'm following the README.md guide but unable to start bridgetown in localhost due to a message:

```
[Bridgetown] Stopping auxiliary processes...
[Bridgetown]   Exception raised: Liquid::SyntaxError
[Bridgetown] Liquid syntax error (line 6): Unknown tag 'plausible'
[Bridgetown]                  1: /usr/local/lib/ruby/gems/gems/liquid-5.4.0/lib/liquid/document.rb:36:in `unknown_tag'
[Bridgetown]                  2: /usr/local/lib/ruby/gems/gems/liquid-5.4.0/lib/liquid/document.rb:57:in `block in parse_body'
[Bridgetown]                  3: /usr/local/lib/ruby/gems/gems/liquid-5.4.0/lib/liquid/block_body.rb:138:in `parse_for_document'
[Bridgetown]                  4: /usr/local/lib/ruby/gems/gems/liquid-5.4.0/lib/liquid/block_body.rb:29:in `parse'
[Bridgetown]                  5: /usr/local/lib/ruby/gems/gems/liquid-5.4.0/lib/liquid/document.rb:55:in `parse_body'
[Bridgetown]          Backtrace: Use the --trace option for complete information.
```

I install the library using this script:
```
bundle exec bridgetown apply https://github.com/bt-rb/bridgetown-plausible
```

But, since it failed I thought some config might not executed, then I tried:
```
bundle add bridgetown-plausible -g bridgetown_plugins
```

The result was the same. 

Adding `init :"bridgetown-plausible"` like other plugins doesn't crash the app but there's a message:
```
Initializing: The `bridgetown-plausible' initializer could not be found
```

**Comment by whysthatso** [comment]
I believe the plugin is currently not compatible with the new init process.

**Comment by andrewmcodes** [comment]
This should be resolved with v2 release.
